spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: niuoj-backend-user-service
          uri: lb://niuoj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: niuoj-backend-question-service
          uri: lb://niuoj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: niuoj-backend-judge-service
          uri: lb://niuoj-backend-judge-service
          predicates:
            - Path=/api/judge/**

  application:
    name: niuoj-backend-gateway
  main:
    web-application-type: reactive
server:
  port: 8101
knife4j:
  gateway:
    # ① 开启gateway聚合组件
    enabled: true
    # ② 设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 开启discover模式
      enabled: true
      # ④ 聚合子服务全部为Swagger2规范的文档
      version: swagger2
